name: Build Stencil Playwright

on:
  workflow_call:
  # Make this a reusable workflow, no value needed
  # https://docs.github.com/en/actions/using-workflows/reusing-workflows

jobs:
  build_stencil_playwright:
    name: Build Stencil Playwright
    runs-on: 'ubuntu-22.04'
    steps:
      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          # the pull_request_target event will consider the HEAD of `main` to be the SHA to use.
          # attempt to use the SHA associated with a pull request and fallback to HEAD of `main`
          ref: ${{ github.event_name == 'pull_request_target' && format('refs/pull/{0}/merge', github.event.number) || '' }}
          persist-credentials: false

      - name: ğŸ•¸ï¸ Get Core Dependencies
        uses: ./.github/workflows/actions/get-core-dependencies

      - name: ğŸ—ï¸ Stencil Playwright Build
        run: npm run build
        shell: bash

      - name: ğŸ“¤ Upload Build Artifacts
        uses: ./.github/workflows/actions/upload-archive
        with:
          name: stencil-playwright
          output: stencil-playwright-build.zip
          paths: dist/

