name: 'Stencil Playwright Production Release'

on:
  workflow_call:
    inputs:
      tag:
        required: false
        default: latest
        type: string
        description: Which npm tag should this be published to? (latest or dev)

permissions:
  contents: write
  id-token: write

jobs:
  build_stencil_playwright:
    name: üèóÔ∏è Build
    uses: ./.github/workflows/build.yml

  release_stencil_playwright_production_build:
    name: üöÄ Publish Stencil Playwright (Production)
    needs: [build_stencil_playwright]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      # Log the input from GitHub Actions for easy traceability
      - name: üìù Log GitHub Workflow UI Input
        run: |
          echo "Tag: ${{ inputs.tag }}"
        shell: bash

      - name: üì• Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: 'main'

      - name: üè∑Ô∏è Get the Version String
        id: version_retrieval
        run: |
          VERSION_STR=$(jq '.version' package.json | sed s/\"//g)
          echo "VERSION_STR=$VERSION_STR" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: üñ®Ô∏è Print Version String
        run: |
          echo Version: ${{ steps.version_retrieval.outputs.VERSION_STR }}
        shell: bash

      - uses: ./.github/workflows/publish-npm.yml
        with:
          tag: ${{ inputs.tag }}
          version: ${{ steps.version_retrieval.outputs.VERSION_STR }}

