name: 'Dev Release'

on:
  workflow_call:

permissions:
  contents: read
  id-token: write

jobs:
  build_stencil_playwright:
    name: ðŸ—ï¸ Build
    uses: ./.github/workflows/build.yml

  get_dev_version:
    name: ðŸ·ï¸ Get Dev Build Version
    runs-on: ubuntu-latest
    outputs:
      dev-version: ${{ steps.generate-dev-version.outputs.DEV_VERSION }}
    steps:
      - name: ðŸ“¥ Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: ðŸ·ï¸ Generate Dev Version
        id: generate-dev-version
        run: |
          PKG_JSON_VERSION=$(cat package.json | jq -r '.version')
          GIT_HASH=$(git rev-parse --short HEAD)

          # A unique string to publish Stencil Playwright under
          # e.g. "2.1.0-dev.1677185104.7c87e34"
          DEV_VERSION=$PKG_JSON_VERSION-dev.$(date +"%s").$GIT_HASH

          echo "Using version $DEV_VERSION"

          # store a key/value pair in GITHUB_OUTPUT
          # e.g. "DEV_VERSION=2.1.0-dev.1677185104.7c87e34"
          echo "DEV_VERSION=$DEV_VERSION" >> $GITHUB_OUTPUT
        shell: bash

  release_stencil_playwright:
    name: ðŸ“¦ Publish Dev Build
    needs: [build_stencil_playwright, get_dev_version]
    uses: ./.github/workflows/publish-npm.yml
    with:
      tag: dev
      version: ${{ needs.get_dev_version.outputs.dev-version }}

